[build]
#  command="# no build command"
#  functions="netlify/functions"
  publish="public"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/trips"
  to = "/.netlify/functions/trips"

[[redirects]]
  from = "/trip-details"
  to = "/.netlify/functions/trip-details"  